import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import variables from "@/styles/variables.module.scss";
import Header from "@/components/Header";
import "./global.css";
import Providers from "@/providers";

const interTight = Inter_Tight({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={interTight.className} lang="en">
      <body>
        <main className={variables.layout}>
          <Providers>
            <Header />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
